server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: payment_route
#          uri: http://localhost:8001
          uri: lb://cloud-eureka-payment-service
          predicates:
            - Path=/payment/getById/**
            - After=2020-10-10T09:43:21.519+08:00[Asia/Shanghai]

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-eureka-payment-service
          predicates:
            - Path=/payment/timeout



eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
